apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stockhub
spec:
  ingressClassName: __INGRESS_CLASS__
  tls:
    - hosts: [__STOCKHUB_HOST__]
      secretName: stockhub-tls
  rules:
    - host: __STOCKHUB_HOST__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stockhub
                port:
                  name: http
